spring.application.name=lab-delivery
# Servidor MongoDB local (instalado no laboratorio ou em conteiner)
spring.data.mongodb.uri=mongodb://localhost:27017/delivery
# Necessario para que @Indexed(unique = true) gere o indice na inicializacao
spring.data.mongodb.auto-index-creation=true
# Exibe no console os comandos enviados ao MongoDB
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
